//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCESS
    {
        public long IdAccess { get; set; }
        public System.DateTime DateEntry { get; set; }
        public Nullable<System.DateTime> DateExit { get; set; }
    
        public virtual STATION STATION { get; set; }
        public virtual USER USER { get; set; }
    }
}
