//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransporteModalEntities : DbContext
    {
        public TransporteModalEntities()
            : base("name=TransporteModalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<STATION> STATION { get; set; }
        public virtual DbSet<TYPESTATION> TYPESTATION { get; set; }
        public virtual DbSet<TYPEVEHICLE> TYPEVEHICLE { get; set; }
        public virtual DbSet<VEHICLE> VEHICLE { get; set; }
        public virtual DbSet<ZONE> ZONE { get; set; }
        public virtual DbSet<USER> USER { get; set; }
        public virtual DbSet<ACCESS> ACCESS { get; set; }
    }
}
